# Generated by Django 2.2.4 on 2019-09-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=50, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lasttime', models.DateTimeField()),
            ],
        ),
    ]
