# Generated by Django 2.2.4 on 2019-09-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=50)),
                ('lasttime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.IntegerField(max_length=10)),
                ('title', models.CharField(max_length=30)),
                ('title_font_color', models.CharField(max_length=8, null=True)),
                ('thumb', models.CharField(max_length=255)),
                ('num', models.IntegerField(max_length=10)),
                ('lasttime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='news_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newid', models.IntegerField(max_length=10)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='position_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionid', models.IntegerField(max_length=10)),
                ('newsid', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='main',
        ),
    ]
