# Generated by Django 2.2.4 on 2019-10-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190929_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='briefInfo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='heading',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
